from __future__ import annotations

import typing

import amulet.nbt

__all__: list[str] = ["BedrockLevelDat"]

class BedrockLevelDat:
    named_tag: amulet.nbt.NamedTag
    @staticmethod
    def from_binary(buffer: bytes) -> BedrockLevelDat: ...
    @staticmethod
    def from_file(path: str) -> BedrockLevelDat: ...
    def __copy__(self) -> BedrockLevelDat: ...
    def __deepcopy__(self, memo: dict) -> BedrockLevelDat: ...
    def __init__(
        self, version: typing.SupportsInt, named_tag: amulet.nbt.NamedTag
    ) -> None: ...
    def __repr__(self) -> str: ...
    def save_to(self, path: str) -> None: ...
    def to_binary(self) -> bytes: ...
    @property
    def version(self) -> int: ...
    @version.setter
    def version(self, arg0: typing.SupportsInt) -> None: ...
